package org.usfirst.frc2609.Bendgate.commands;

import edu.wpi.first.wpilibj.Encoder;
import edu.wpi.first.wpilibj.command.Command;
import org.usfirst.frc2609.Bendgate.Robot;
import org.usfirst.frc2609.Bendgate.RobotMap;
import org.usfirst.frc2609.Bendgate.subsystems.robotDrive;

import com.kauailabs.navx.frc.AHRS;


public class  driveAngleTurn extends Command {
	AHRS ahrs = robotDrive.ahrs;
	private double driveHeading;
    public driveAngleTurn(double driveHeading) {
    	this.driveHeading = driveHeading;
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        requires(Robot.robotDrive);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }

    // Called just before this Command runs the first time
    protected void initialize() {
    	Robot.robotDrive.disable();
    	Robot.robotDrive.setOutputRange(-.5, .5);
    	Robot.robotDrive.robotDriveHeading = driveHeading;
        Robot.robotDrive.bendTurn();
    }

    // Called repeatedly when this Command is scheduled to run
    protected void execute() {
    	Robot.robotDrive.bendTurn();
    }

    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
    	if (ahrs.getYaw()==driveHeading){
    		return true;
    	}
    	else{
    		return false;
    	}
    }

    // Called once after isFinished returns true
    protected void end() {
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {
    }
}
