package org.usfirst.frc2609.Bendgate.commands;

import edu.wpi.first.wpilibj.DigitalInput;
import edu.wpi.first.wpilibj.Timer;
import edu.wpi.first.wpilibj.command.Command;
import edu.wpi.first.wpilibj.command.CommandGroup;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;

import org.usfirst.frc2609.Bendgate.OI;
import org.usfirst.frc2609.Bendgate.Robot;
import org.usfirst.frc2609.Bendgate.RobotMap;


public class  rollerIn extends Command {
    DigitalInput toteSenseR = RobotMap.toteSenseR;
    DigitalInput toteSenseL = RobotMap.toteSenseL;
    public rollerIn() {

        // Use requires() here to declare subsystem dependencies
        // eg. requires(chassis);

        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        requires(Robot.rollerDrive);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }

    // Called just before this Command runs the first time
    protected void initialize() {
    }

    // Called repeatedly when this Command is scheduled to run
    protected void execute() {
    	Robot.rollerDrive.rollIn();
    	/*if (toteSenseR.get() == true || toteSenseL.get() == true ){
    		Robot.rollerDrive.rollIn();}
    	else{
    		Robot.rollerDrive.rollStop();
    	}*/
        SmartDashboard.putBoolean("toteSenseR 2", toteSenseR.get());
        SmartDashboard.putBoolean("toteSenseL 2", toteSenseL.get());
    	//Timer.delay(0.1);
    	//Robot.rollerDrive.rollStop();
    	//Timer.delay(0.01);
        
    }

   
    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
        return (!(toteSenseR.get() || toteSenseL.get()));
    }

    // Called once after isFinished returns true
    protected void end() {
    	Robot.rollerDrive.rollStop();
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {
    }
}

