package org.usfirst.frc2609.BendGate.subsystems;

import org.usfirst.frc2609.BendGate.OI;
import org.usfirst.frc2609.BendGate.Robot;
import org.usfirst.frc2609.BendGate.RobotMap;
import org.usfirst.frc2609.BendGate.commands.*;
import edu.wpi.first.wpilibj.*;
import edu.wpi.first.wpilibj.CounterBase.EncodingType; import edu.wpi.first.wpilibj.PIDSource.PIDSourceParameter;
import edu.wpi.first.wpilibj.can.*;
import edu.wpi.first.wpilibj.Joystick;
import edu.wpi.first.wpilibj.command.Subsystem;


/**
 *
 */
public class Drive extends Subsystem {
	CANTalon cANTalonLF = RobotMap.driveCANTalonLF;
    CANTalon cANTalonLR = RobotMap.driveCANTalonLR;
    CANTalon cANTalonRF = RobotMap.driveCANTalonRF;
    CANTalon cANTalonRR = RobotMap.driveCANTalonRR;
    RobotDrive RobotDrive4 = RobotMap.RobotDrive4;
    Encoder quadratureEncoderLeft = RobotMap.drivequadratureEncoderLeft;
    Encoder quadratureEncoderRight = RobotMap.drivequadratureEncoderRight;
    Gyro gyro1 = RobotMap.driveGyro1;


    // Put methods for controlling this subsystem
    // here. Call these from Commands.
    public void BendDrive(){
    	
    	RobotDrive4.arcadeDrive(OI.driver.getRawAxis(2),OI.driver.getRawAxis(3),true);
    	// Change it from left stick to right 
    }
    public void driveReset(){
    	quadratureEncoderLeft.reset();
    	quadratureEncoderRight.reset();
    }
    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
	
        // Set the default command for a subsystem here.
        //setDefaultCommand(new MySpecialCommand());
    }
}

