package org.usfirst.frc2609.BendGate.subsystems;

import org.usfirst.frc2609.BendGate.OI;
import org.usfirst.frc2609.BendGate.Robot;
import org.usfirst.frc2609.BendGate.RobotMap;
import org.usfirst.frc2609.BendGate.commands.*;
import edu.wpi.first.wpilibj.*;
import edu.wpi.first.wpilibj.Joystick;
import edu.wpi.first.wpilibj.command.Command;
import edu.wpi.first.wpilibj.command.Subsystem;


/**
 *
 */
public class Rollers extends Subsystem {
    SpeedController rollerLeft = RobotMap.rollersrollerLeft;
    SpeedController rollerRight = RobotMap.rollersrollerRight;

    
	public void rollIn(){
		rollerLeft.set(-.5);
		rollerRight.set(.5);
	}
	public void rollStop(){
		rollerLeft.set(0);
		rollerRight.set(0);
	}
	public void rollOut(){
		rollerLeft.set(.5);
		rollerRight.set(-.5);
	}

    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        // Set the default command for a subsystem here.
        //setDefaultCommand(new Robot.rollers.rollStop());

    }
    
}



